
CREATE SEQUENCE ACME_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCACHE
    NOORDER
;
GRANT SELECT ON ACME_SEQ TO NSFS_APP
;

CREATE TABLE ACCOUNT(
  ID NUMBER(19,0) DEFAULT ACME_SEQ.NEXTVAL NOT NULL,
  NAME VARCHAR(25)
)
TABLESPACE NSFS_TABLES;
GRANT DELETE ON NSFS.PARTY TO CRUD
;
GRANT INSERT ON NSFS.PARTY TO CRUD
;
GRANT SELECT ON NSFS.PARTY TO CRUD
;
GRANT UPDATE ON NSFS.PARTY TO CRUD
;

ALTER TABLE ACCOUNT ADD
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID)
;

CREATE TABLE TASK(
  ID NUMBER(19,0) DEFAULT ACME_SEQ.NEXTVAL NOT NULL,
  INDEX NUMBER(6,0)
)
TABLESPACE NSFS_TABLES;
GRANT DELETE ON NSFS.PARTY TO CRUD
;
GRANT INSERT ON NSFS.PARTY TO CRUD
;
GRANT SELECT ON NSFS.PARTY TO CRUD
;
GRANT UPDATE ON NSFS.PARTY TO CRUD
;

ALTER TABLE TASK ADD
    CONSTRAINT TASK_PK PRIMARY KEY (ID)
;